language: node_js
node_js:
- '9'
sudo: false
dist: trusty
addons:
  chrome: stable
cache:
  yarn: true
env:
  global:
  - JOBS=1
  - secure: YCcIDw+mcoJW1DpHMB5VGlueOM1HbJl3fHvrASAN1A5Mj807P/9L5Wzj+Gwa79CHXZbIRA+uyOsxGICbd06NRiYGQTYtm5DYBnVazyyL/uYCytHRDCirbE6cJGg6egczC/Vuv0UhhznPDWj1+ot5ISWcfdYZxh1CZ11Ob8QGHxMaAucpLPRBBH1dP0Bt8yfXBDGaGyUDZ1GqNuqMYOq2LMS36QoGW29uwiAXqEJM8TD4Tu264vf7ex3Ua7l/mcLYuHONbVr1DPCL89zfu831k+5T0XP/mWV8t5G6mzqNJ1j1Ns0f/Xnqa7Hp1/B2Loc2xgHOXY6T6LZEFSard8VXy/2gZIJoigmb+yG8sdfjhqyS3GE5r0NASASs72h6MW2ltdvNRy8Mc2nmHpj0Zjw9AUCMeR+MaeIKlvv1Cb4eYScoe34CVpbQxFqQwgzrMU8uNm5uGN4KGhal08HrkkPWBjLTTy0GUpWa1Qz21hadX4c0YSBo7Xhn5zntGMDoh8nDJV5uzNHq3RhrD1gXS+7iCnrVTLU7TwvcIvrDKyKKUZBHoP+YW0S7sVn8kcU3bcqlsJpIRf+sNtwSUHrJvrQ+0fZYDKriwxnNccB898aGPJ2dg+gAxYx7rgg/kdAHGX8MusdXbEok+tytiXSAboispsygNl/6zTkXxjvf/lVGpn4=
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
- yarn global add bower
install:
- yarn install --non-interactive
before_script:
- ember sauce:connect
script:
- yarn lint:js
- yarn test-ci
after_script:
- ember sauce:disconnect
