on: pull_request
name: ZH Automation - PR Manage
jobs:
  call_zh_automations:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: call_zh_automations
      uses: james1x0/zenhub-automations@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        INPROG_COLUMN: 5c92522983c46e630dc18372
        PR_COLUMN: 5c92522983c46e630dc18373
        REVIEW_COLUMN: 5c92522983c46e630dc18373
        ZENHUB_API_KEY: ${{ secrets.ZENHUB_API_KEY }}
